apiVersion: v1
data:
  Corefile: |
    .:53 {
        errors
        health {
           lameduck 5s
        }
        ready
        kubernetes cluster.local in-addr.arpa ip6.arpa {
           pods insecure
           fallthrough in-addr.arpa ip6.arpa
           ttl 30
        }
        prometheus :9153
        forward . /etc/resolv.conf {
           max_concurrent 1000
        }
        cache 30 {
           disable success cluster.local
           disable denial cluster.local
        }
        loop
        reload
        loadbalance
        hosts {
          172.22.209.105 proxy.util.lcl gitea.util.lcl ldapui.util.lcl harbor.util.lcl keycloak.util.lcl rancher.util.lcl 
          fallthrough
        }
        # # Add this block for external DNS resolution
        # util.lcl:53 {
        #   forward . 10.163.169.180
        # }
    }
kind: ConfigMap
metadata:
  name: coredns
  namespace: kube-system