---
rke2_node_prepare_enabled: false

rke2_node_prepare_kernel_modules:
  - overlay
  - br_netfilter

rke2_node_prepare_sysctl:
  net.bridge.bridge-nf-call-iptables: 1
  net.bridge.bridge-nf-call-ip6tables: 1
  net.ipv4.ip_forward: 1

rke2_node_prepare_disable_swap: true
rke2_node_prepare_disable_firewall: true
